#FST: main.c FST.c
#	gcc	-g -o FST FST.c main.c -lm -DDEBUG

#FST: main.c FST.c
#	gcc	-g -o FST FST.c main.c -fopenmp -lm -Wall -DDEBUG

FST: main.c FST.c
	gcc	-g -o FST FST.c main.c -fopenmp -lm -Wall 
